name: Monitoraggio Wallet e Token

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte
  push:
    branches:
      - main  # Oppure usa un altro trigger come `workflow_dispatch` per eseguirlo manualmente

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v4  # Usa la versione più recente v4 di actions/checkout
      
      # Set up Python (versione v4 per compatibilità con node20)
      - name: Set up Python
        uses: actions/setup-python@v4  # Versione aggiornata per Node.js 20
        with:
          python-version: '3.x'

      # Installa le dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install solana

      # Esegui lo script Python
      - name: Run the script
        run: |
          python monitor_wallets.py  # Modifica con il nome del tuo script

      # Carica il file di analisi come artefatto
      - name: Upload analysis file as artifact
        uses: actions/upload-artifact@v3  # Usa la versione v3 per compatibilità con Node.js 20
        with:
          name: wallet-analysis
          path: analisi_*.txt  # Carica tutti i file che corrispondono al pattern
